"""Added table to store audio files data

Revision ID: dbc57fcdc0e5
Revises: a8c94d2f2887
Create Date: 2025-12-29 20:33:17.122619

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "dbc57fcdc0e5"
down_revision: Union[str, None] = "a8c94d2f2887"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
