"""timezone update in created_at column

Revision ID: ef8ca2d0487f
Revises: dbc57fcdc0e5
Create Date: 2025-12-29 20:37:12.475917

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ef8ca2d0487f"
down_revision: Union[str, None] = "dbc57fcdc0e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
