"""Updating relationship one to many

Revision ID: fd870935df32
Revises: decbb1a233af
Create Date: 2025-12-29 21:54:22.701945

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "fd870935df32"
down_revision: Union[str, None] = "decbb1a233af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
